"""Step 20 - the summary table of every cell appendix E estimates.

Appendix E reports dozens of estimates across its eight tests, and a reader who
meets one of them in a Result block has no way to place it among the rest. This
script emits one table holding all of them: every conversation boundary, in every
partition of a game, on both samples, under the ElasticNet with the appendix's
default controls.

An entry is bold where the cross-validated and the held-out estimate both clear
zero in the same direction, which is the standard the appendix applies throughout.

Outputs:
  * ``outputs/tables/windows/appendix_cells_table.tex`` - the table body

Run:  python scripts/20_appendix_cells_table.py
"""

import csv
from pathlib import Path

TABLES = Path(__file__).resolve().parents[1] / "outputs" / "tables"
SOURCE = TABLES / "windows" / "block_delta_r2.csv"
THIRDS = TABLES / "round_stage.csv"
OUT = TABLES / "windows" / "appendix_cells_table.tex"

FAMILY, CONTROLS = "elastic net", "rules+timing"
BLOCKS = ["pre", "post", "window", "cumulative"]
BLOCK_LABEL = {"pre": "Pre", "post": "Post",
               "window": "Window", "cumulative": "Cumulative"}
BINS = ["all rounds", "opening", "middle", "endgame",
        "early", "middle third", "late",
        "round 1", "round 2", "round 3", "rounds 4-6", "rounds 7-10", "rounds 11+"]
# The proportional partition is fitted by step 4, on conversing rounds only, and
# without the Cumulative boundary; its rows are read from a different table.
THIRDS_BINS = {"early": "early", "middle third": "middle", "late": "late"}
BIN_LABEL = {"all rounds": "All rounds", "opening": "Opening", "middle": "Middle",
             "endgame": "Endgame", "early": "First third",
             "middle third": "Second third", "late": "Last third",
             "round 1": "Round 1", "round 2": "Round 2",
             "round 3": "Round 3", "rounds 4-6": "Rounds 4--6",
             "rounds 7-10": "Rounds 7--10", "rounds 11+": "Rounds 11+"}

# Where each group of rows is discussed. A section is cited on the first row that
# needs it and left blank afterwards.
SECTION = {"opening": "cs_wider", "middle": "cs_wider", "endgame": "cs_wider",
           "early": "cs_thirds", "middle third": "cs_thirds", "late": "cs_thirds",
           "round 1": "cs_round_bins", "round 2": "cs_round_bins",
           "round 3": "cs_round_bins", "rounds 4-6": "cs_round_bins",
           "rounds 7-10": "cs_round_bins", "rounds 11+": "cs_round_bins"}
SAMPLE_SECTION = {"talkers": "cs_talkers"}
SAMPLES = ["channel", "talkers"]
SAMPLE_LABEL = {"channel": "Channel", "talkers": "Conversing"}


def load():
    cells = {}
    with SOURCE.open() as fh:
        for row in csv.DictReader(fh):
            if row["model_family"] != FAMILY or row["controls"] != CONTROLS:
                continue
            cells[(row["bin"], row["block"], row["sample"])] = row
    inverse = {v: k for k, v in THIRDS_BINS.items()}
    with THIRDS.open() as fh:
        for row in csv.DictReader(fh):
            if row["staging"] != "relative" or row["model_family"] != FAMILY:
                continue
            cells[(inverse[row["stage"]], row["block"], "talkers")] = {
                "delta_cv_r2": row["delta_cv_r2_content"],
                "delta_heldout_r2": row["delta_heldout_r2_content"],
                "ci_low": row["ci_low"], "ci_high": row["ci_high"],
                "ci_low_heldout": row["ci_low_heldout"],
                "ci_high_heldout": row["ci_high_heldout"]}
    return cells


def clears(low, high):
    """+1, -1 or 0: the direction the interval is bounded away from zero in."""
    if low > 0:
        return 1
    if high < 0:
        return -1
    return 0


def entry(row):
    """The two estimates for one cell, bold where both clear zero the same way."""
    if row is None:
        return "--", "--"
    cv, ho = float(row["delta_cv_r2"]), float(row["delta_heldout_r2"])
    both = (clears(float(row["ci_low"]), float(row["ci_high"]))
            == clears(float(row["ci_low_heldout"]), float(row["ci_high_heldout"]))
            != 0)
    fmt = (lambda v: f"\\textbf{{{v:+.3f}}}") if both else (lambda v: f"{v:+.3f}")
    return fmt(cv), fmt(ho)


def main():
    cells = load()
    ncols = 3 + 2 * len(BLOCKS)
    header_cols = " & ".join(f"\\multicolumn{{2}}{{c}}{{\\textbf{{{BLOCK_LABEL[b]}}}}}"
                             for b in BLOCKS)
    cmid = "".join(f"\\cmidrule(lr){{{3 + 2 * i}-{4 + 2 * i}}}"
                   for i in range(len(BLOCKS)))
    lines = [
        "% Generated by scripts/20_appendix_cells_table.py from",
        "% outputs/tables/windows/block_delta_r2.csv and outputs/tables/round_stage.csv.",
        "% Do not edit by hand; re-run the script instead.",
        "\\begin{table}[ht]",
        "\\centering",
        "\\caption{\\textbf{Additional $R^2$ from Conversation, for Every Cell of the Design.}"
        " Each entry is the variance in a group's mean contribution explained by its conversation"
        " beyond the base model, under the ElasticNet. Learn is the cross-validated estimate within"
        " the learning split; Val is the estimate scored on the held-out validation games. Bold"
        " marks the cells where both estimates clear zero in the same direction, the standard this"
        " appendix applies throughout; intervals are given in the section named in the last column,"
        " cited on the first row it covers. Post in round 1 on the conversing sample has no rows,"
        " and the proportional thirds were fitted on conversing rounds only, without the Cumulative"
        " boundary."
        "\\label{tab:appendix_cells}}",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\begin{tabular}{ll" + "rr" * len(BLOCKS) + "l}",
        "\\toprule",
        " & & " + header_cols + " & \\\\",
        cmid,
        "\\textbf{Time period} & \\textbf{Sample} & "
        + " & ".join(["\\textbf{Learn} & \\textbf{Val}"] * len(BLOCKS))
        + " & \\textbf{Details} \\\\",
        "\\midrule",
    ]
    cited = set()
    for i, b in enumerate(BINS):
        if i:
            lines.append("\\addlinespace[2pt]")
        first = True
        for sample in SAMPLES:
            values = []
            for block in BLOCKS:
                values.extend(entry(cells.get((b, block, sample))))
            if all(v == "--" for v in values):
                continue
            label, first = (BIN_LABEL[b] if first else ""), False
            section = SAMPLE_SECTION.get(sample) if b in ("opening", "middle",
                                                          "endgame") else None
            section = section or SECTION.get(b)
            if section in cited:
                section = ""
            elif section:
                cited.add(section)
                section = f"\\S\\ref{{{section}}}"
            lines.append(f"{label} & {SAMPLE_LABEL[sample]} & "
                         + " & ".join(values) + f" & {section or ''} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    OUT.write_text("\n".join(lines) + "\n")
    fitted = sum(1 for b in BINS for bl in BLOCKS for s in SAMPLES
                 if (b, bl, s) in cells)
    print(f"wrote {OUT.relative_to(TABLES.parents[1])}: {fitted} cells")


if __name__ == "__main__":
    main()
