"""Step 21 - the short-game restriction table appendix E reports.

Games shorter than seven rounds put the same rounds on both sides of the
Opening/Endgame contrast, so the test refits each time period on games of at
least seven rounds and then at least 11. This script emits that table from the
scope run rather than leaving the numbers to be copied by hand.

An estimate is bold where its interval excludes zero.

Outputs:
  * ``outputs/tables/short_game_table.tex`` - the table the appendix includes

Run:  python scripts/21_short_game_table.py
"""

import csv
from pathlib import Path

TABLES = Path(__file__).resolve().parents[1] / "outputs" / "tables"
SOURCE = TABLES / "short_game_scope.csv"
OUT = TABLES / "short_game_table.tex"

ROWS = [("opening", 7), ("opening", 11), ("endgame", 7), ("endgame", 11)]
STAGE_LABEL = {"opening": "Opening", "endgame": "Endgame"}


def estimate(row, prefix=""):
    mid = float(row[f"delta_{'heldout_' if prefix else 'cv_'}r2"])
    lo = float(row[f"ci_low{'_heldout' if prefix else ''}"])
    hi = float(row[f"ci_high{'_heldout' if prefix else ''}"])
    if lo > 0 or hi < 0:
        # \textbf does not reach inside math mode, so bold the numbers themselves.
        return f"$\\boldsymbol{{{mid:+.3f}}}$ $\\boldsymbol{{[{lo:.3f}, {hi:.3f}]}}$"
    return f"${mid:+.3f}$ $[{lo:.3f}, {hi:.3f}]$"


def main():
    with SOURCE.open() as fh:
        data = {(r["stage"], int(r["min_rounds"])): r for r in csv.DictReader(fh)}
    lines = [
        "% Generated by scripts/21_short_game_table.py from",
        "% outputs/tables/short_game_scope.csv.",
        "% Do not edit by hand; re-run the script instead.",
        "\\begin{table}[ht]",
        "\\centering",
        "\\caption{\\textbf{The Opening and Endgame Refitted on Longer Games.}"
        " Additional $R^2$ from conversation, on the conversing sample under the"
        " ElasticNet, for games of at least seven and at least 11 rounds. Learn is"
        " cross-validated within the learning split; Val is scored on the held-out"
        " validation games. Bold marks an interval that excludes zero."
        "\\label{tab:short_games}}",
        "\\footnotesize",
        "\\begin{tabular}{llrll}",
        "\\toprule",
        "\\textbf{Time period} & \\textbf{Games kept} & \\textbf{Convs.\\ (games)}"
        " & \\textbf{Learn} & \\textbf{Val} \\\\",
        "\\midrule",
    ]
    for i, (stage, floor) in enumerate(ROWS):
        if i == len(ROWS) // 2:
            lines.append("\\midrule")
        r = data[(stage, floor)]
        lines.append(
            f"{STAGE_LABEL[stage]} & $\\geq {floor}$ rounds & "
            f"{r['n_rounds']} ({r['n_games']}) & "
            f"{estimate(r)} & {estimate(r, 'heldout')} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(TABLES.parents[1])}")


if __name__ == "__main__":
    main()
